#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    u4cnnwrf
#
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Tue Oct 09 06:46:17 2018
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass

def main():
  
    run_command("g.region",
                vector = "blws_65r@report")
# 42  
#     run_command("v.overlay",
#                 ainput = "blws_65r_pad@report",
#                 alayer = "1",
#                 atype = "auto",
#                 binput = "blws_65r_42@report",
#                 blayer = "1",
#                 btype = "area",
#                 operator = "or",
#                 output = "blws_pad42",
#                 olayer = "1,0,0",
#                 snap = 1e-8)
# 
#     run_command("v.db.addcolumn",
#                 map = "blws_pad42",
#                 layer = "1",
#                 columns = "subarea double precision")
# 
#     run_command("v.to.db",
#                 map = "blws_pad42",
#                 layer = "1",
#                 type = "point,line,boundary,centroid",
#                 option = "area",
#                 columns = "subarea",
#                 query_layer = "1",
#                 separator = "pipe")
# 31
#     run_command("v.overlay",
#                 ainput = "blws_65r_pad@report",
#                 alayer = "1",
#                 atype = "auto",
#                 binput = "blws_31c@report",
#                 blayer = "1",
#                 btype = "area",
#                 operator = "or",
#                 output = "blws_pad31",
#                 olayer = "1,0,0",
#                 snap = 1e-8)
# 
#     run_command("v.db.addcolumn",
#                 map = "blws_pad31",
#                 layer = "1",
#                 columns = "subarea double precision")
# 
#     run_command("v.to.db",
#                 map = "blws_pad31",
#                 layer = "1",
#                 type = "point,line,boundary,centroid",
#                 option = "area",
#                 columns = "subarea",
#                 query_layer = "1",
#                 separator = "pipe")

# 41
#     run_command("v.overlay",
#                 ainput = "blws_65r_pad@report",
#                 alayer = "1",
#                 atype = "auto",
#                 binput = "blws_65r_41@report",
#                 blayer = "1",
#                 btype = "area",
#                 operator = "or",
#                 output = "blws_pad41",
#                 olayer = "1,0,0",
#                 snap = 1e-8)
# 
#     run_command("v.db.addcolumn",
#                 map = "blws_pad41",
#                 layer = "1",
#                 columns = "subarea double precision")
# 
#     run_command("v.to.db",
#                 map = "blws_pad41",
#                 layer = "1",
#                 type = "point,line,boundary,centroid",
#                 option = "area",
#                 columns = "subarea",
#                 query_layer = "1",
#                 separator = "pipe")

# 71
    run_command("v.overlay",
                ainput = "blws_65r_pad@report",
                alayer = "1",
                atype = "auto",
                binput = "blws_71@report",
                blayer = "1",
                btype = "area",
                operator = "or",
                output = "blws_pad71",
                olayer = "1,0,0",
                snap = 1e-8)

    run_command("v.db.addcolumn",
                map = "blws_pad71",
                layer = "1",
                columns = "subarea double precision")

    run_command("v.to.db",
                map = "blws_pad71",
                layer = "1",
                type = "point,line,boundary,centroid",
                option = "area",
                columns = "subarea",
                query_layer = "1",
                separator = "pipe")


    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
