#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    Will Fields
#
# PURPOSE:      Delineates habitat networks for Camp Dawson
#
# DATE:         Tue Sep 11, 2018
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass
# 
def main():
# Set region & mask
  run_command("g.region",
                vector = 'cdaw_65r')

  run_command("r.mask",
                maskcats = "*",
                vector = 'cdaw_65r',
                layer = "1")
# 
# # mapcalcs for habitat networks from rasters
  run_command("r.mapcalc",
                expression = 'cdaw_65r' + "_tmpvd=if(us_140vdep<67,1,null())",
                overwrite = True)

#  
  run_command("r.mapcalc",
                expression = 'cdaw_65r' + '_tmp43=if(nlcd_2011v14==43,1,null())',
                overwrite = True)

  run_command("r.mapcalc",
                expression = 'cdaw_65r' + "_tmp41=if(nlcd_2011v14@PERMANENT==41,1,null())",
                overwrite = True)
                
  run_command("r.mapcalc",
                expression = 'cdaw_65r' + "_tmp41424390=if(nlcd_2011v14@PERMANENT==41 || nlcd_2011v14@PERMANENT==42 || nlcd_2011v14@PERMANENT==43 || nlcd_2011v14@PERMANENT==90,1,null())",
                overwrite = True)


# multiply vdep & nlcd
  run_command("r.mapcalc",
                expression = 'cdaw_65r' + "_43=" + 'cdaw_65r' + "_tmpvd * " + 'cdaw_65r' + "_tmp43",
                overwrite = True)

  run_command("r.mapcalc",
                expression = 'cdaw_65r' + "_41=" + 'cdaw_65r' + "_tmpvd * " + 'cdaw_65r' + "_tmp41",
                overwrite = True)
                
  run_command("r.mapcalc",
                expression = 'cdaw_65r' + "_41424390=" + 'cdaw_65r' + "_tmpvd * " + 'cdaw_65r' + "_tmp41424390",
                overwrite = True)


# write data to vector       
  run_command("r.to.vect",
                input = 'cdaw_65r_43',
                output = 'cdaw_65r_43',
                type= "area")         

  run_command("r.to.vect",
                input = 'cdaw_65r_41',
                output = 'cdaw_65r_41',
                type= "area")         

  run_command("r.to.vect",
                input = 'cdaw_65r_41424390',
                output = 'cdaw_65r_41424390',
                type= "area")         

                
# remove raster mask
  run_command("r.mask",
                flags = 'r',
                maskcats = "*",
                layer = "1")

  return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
