#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    Will Fields
#
# PURPOSE:      Delineates habitat networks for Geocarpon @ Chaffee
#
# DATE:         Tue Sep 11, 2018
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass
# 
def main():
# Set region & mask
  run_command("g.region",
                vector = 'fccg_65r')

  run_command("r.mask",
                maskcats = "*",
                vector = 'fccg_65r',
                layer = "1")

# # mapcalcs for habitat networks from rasters
#   run_command("r.mapcalc",
#                 expression = 'fc_65r' + "_tmpvd=if(us_140vdep<67,1,null())",
#                 overwrite = True)
# #  
#   run_command("r.mapcalc",
#                 expression = 'fc_65r' + "_tmp41424390=if(nlcd_2011v14@PERMANENT==41 || nlcd_2011v14@PERMANENT==42 || nlcd_2011v14@PERMANENT==43 || nlcd_2011v14@PERMANENT==90,1,null())",
#                 overwrite = True)

  run_command("r.mapcalc",
                expression = 'fc_65r' + "_tmp31=if(nlcd_2011v14@PERMANENT==31,1,null())")
                

# multiply vdep & nlcd
#   run_command("r.mapcalc",
#                 expression = 'fc_65r' + "_41424390=" + 'fc_65r' + "_tmpvd * " + 'fc_65r' + "_tmp41424390",
#                 overwrite = True)
                
  run_command("r.mapcalc",
                expression = 'fc_65r' + "_31=" + 'fc_65r' + "_tmpvd * " + 'fc_65r' + "_tmp31",
                overwrite = True)
                


# write data to vector       
#   run_command("r.to.vect",
#                 input = 'fc_65r_41424390',
#                 output = 'fc_65r_41424390',
#                 type= "area")         

  run_command("r.to.vect",
                input = 'fc_65r_31',
                output = 'fva_65r_31',
                type= "area")         


# remove raster mask
  run_command("r.mask",
                flags = 'r',
                maskcats = "*",
                layer = "1")

  return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
