#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    Will Fields
#
# PURPOSE:      Delineates habitat networks for Fort Stewart
#
# DATE:         Wed Sep 12, 2018
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass
# 
def main():
# Set region & mask
  run_command("g.region",
                vector = 'fs_65r')

  run_command("r.mask",
                maskcats = "*",
                vector = 'fs_65r',
                layer = "1")

# # mapcalcs for habitat networks from rasters
  run_command("r.mapcalc",
                expression = 'fs_65r' + "_tmpvd=if(us_140vdep<67,1,null())",
                overwrite = True)
# #  
  run_command("r.mapcalc",
                 expression = 'fs_65r' + "_tmp42=if(nlcd_2011v14@PERMANENT==42,1,null())",
                 overwrite = True)

  run_command("r.mapcalc",
                expression = 'fs_65r' + "_tmp71=if(nlcd_2011v14@PERMANENT==71,1,null())",
                overwrite = True)
                
  run_command("r.mapcalc",
                expression = 'fs_65r' + "_tmp95=if(nlcd_2011v14@PERMANENT==95,1,null())",
                overwrite = True)

# multiply vdep & nlcd
  run_command("r.mapcalc",
                expression = 'fs_65r' + "_42=" + 'fs_65r' + "_tmpvd * " + 'fs_65r' + "_tmp42",
                overwrite = True)

  run_command("r.mapcalc",
                expression = 'fs_65r' + "_71=" + 'fs_65r' + "_tmpvd * " + 'fs_65r' + "_tmp71",
                overwrite = True)
                
  run_command("r.mapcalc",
                expression = 'fs_65r' + "_95=" + 'fs_65r' + "_tmpvd * " + 'fs_65r' + "_tmp95",
                overwrite = True)

# write data to vector       
  run_command("r.to.vect",
                input = 'fs_65r_42',
                output = 'fs_65r_42',
                type= "area",
                overwrite = True)         

  run_command("r.to.vect",
                input = 'fs_65r_71',
                output = 'fs_65r_71',
                type= "area",
                overwrite = True)         

  run_command("r.to.vect",
                input = 'fs_65r_95',
                output = 'fs_65r_95',
                type= "area",
                overwrite = True)         


# remove raster mask
  run_command("r.mask",
                flags = 'r',
                maskcats = "*",
                layer = "1")

  return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
