#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    u4cnnwrf
#
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Thu Sep 13 16:58:01 2018
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass
# 'allen_65r_41424390@report', 'benruc_65r_42@report', 'benruc_65r_90@report', 'benruc_65r_41424390@report', 'benruc_65r_41424390_10@report', 'benruc_65r_41424390_10ha@report', 'benruc_65r_bat20@report', 'bland_65r_42@report', 'bland_65r_52@report', 'bland_65r_95@report', 'blwd_65r_31@report', 'blws_65r_41@report', 'blws_65r_42@report', 'catmer_65r_41@report', 'catmer_65r_43@report', 'catt_65r_43@report', 'catt_65r_41424390@report',
def main():
    for map in [ 'catt_65r_41424390n@report', 'cdaw_65r_41@report', 'cdaw_65r_43@report', 'cdaw_65r_41424390@report', 'ced_65r_41424390@report', 'cm_65r_414271@report', 'cnav_65r_42@report', 'cust_65r_41424390@report', 'cwdp_65r_52@report', 'dix_65r_41424390@report', 'fb_65r_42@report', 'fb_65r_41424390@report', 'fb_65r_nwi@report', 'fb_65r_nwi_rll@report', 'fc_65r_41424390@report', 'fccg_65r_414271@report', 'fccg_65r_41424390@report', 'fcpc_65r_42@report', 'fcpc_65r_42_5@report', 'fcpc_65r_71@report', 'fcpc_65r_71_5@report', 'fd_65r_41424390@report', 'fhctx_65r_41@report', 'fhctx_65r_42@report', 'fhctx_65r_52@report', 'fhctx_65r_52_5@report', 'figab_65r_41424390@report', 'flwo_65r_43@report', 'flwo_65r_41424390@report', 'fp_65r_42@report', 'fp_65r_41424390@report', 'fril_65r_41424390@report', 'fs_65r_42@report', 'fs_65r_71@report', 'fs_65r_95@report', 'fva_65r_31@report', 'fva_65r_41@report', 'fva_65r_42@report', 'fva_65r_43@report', 'fva_65r_41424390@report', 'gorjac_65r_42@report', 'gorjac_65r_43@report', 'gorjac_65r_71@report', 'gorjac_65r_41424390@report', 'graf_65r_41424390@report', 'gray_65r_42@report', 'gray_65r_41424390@report', 'huach_65r_41@report', 'huach_65r_42@report', 'huach_65r_43@report', 'huach_65r_71@report', 'irwin_65r_52@report', 'jblm_cr_65r_42@report', 'jblm_cr_65r_71@report', 'knox_65r_43@report', 'knox_65r_41424390@report', 'mccoy_65r_43@report', 'mccoy_65r_71@report', 'mccoy_65r_41424390@report', 'mta_65r_71@report', 'mta_65r_41424390@report', 'orch_65r_52@report', 'rave_65r_41424390@report', 'rip_65r_42@report', 'rip_65r_41424390@report', 'shel_65r_42@report', 'sill_65r_52@report', 'west_65r_41424390@report']:
        run_command("v.pack",
                    input = map,
                    output = "F:/data/Regional Prioritization/pack/" + map + ".pack")



    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
