#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    u4cnnwrf
#
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Tue Sep 25 15:50:00 2018
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass

def main():
  # allen_65r@report', allen_65r not in mapset??
    for map in ['allen_65r@report','benruc_65r@report', 'bland_65r@report', 'blws_65r@report', 'catmer_65r@report', 'catt_65r@report', 'cdaw_65r@report', 'ced_65r@report', 'cjtr_65r@report', 'cm_65r@report', 'cnav_65r@report', 'cust_65r@report', 'cwdp_65r@report', 'dix_65r@report', 'dodge_65r@report', 'fb_65r@report', 'fc_65r@report', 'fccg_65r@report', 'fcpc_65r@report', 'fd_65r@report', 'fhctx_65r@report', 'figab_65r@report', 'flwo_65r@report', 'fp_65r@report', 'fril_65r@report', 'fs_65r@report', 'fva_65r@report', 'fw_65r@report', 'gorjac_65r@report', 'graf_65r@report', 'gray_65r@report', 'guer_65r@report', 'hlcrslo_65r@report', 'irwin_65r@report', 'jblm_cr_65r@report', 'knox_65r@report', 'macon_65r@report', 'mccoy_65r@report', 'mta_65r@report', 'orch_65r@report', 'prfta_65r@report', 'rave_65r@report', 'rip_65r@report', 'shel_65r@report', 'sill_65r@report', 'west_65r@report', 'will_65r@report', 'yak_65r@report']:
        run_command("g.region", 
                    vector = map)

        run_command("v.clip",
                    input = "padus@report",
                    clip = map,
                    output = map[:-7] + '_pad')



    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
