#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    u4cnnwrf
#
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Thu Sep 13 16:58:01 2018
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass
# no bland_65r_padus?
# ran: 'allen_65r_padus@report', 'benruc_65r_padus@report',  'blws_65r_padus@report', 'catmer_65r_padus@report', 'catt_65r_padus@report',  'cdaw_65r_padus@report', 'ced_65r_padus@report', 'cm_65r_padus@report', 'cnav_65r_padus@report', 'cust_65r_padus@report', 'cwdp_65r_padus@report', 'dix_65r_padus@report', 'fb_65r_padus@report', 'fc_65r_padus@report', 'fccg_65r_padus@report', 'fcpc_65r_padus@report',
# not ran:  'fd_65r_padus@report',
# ran:  'fhctx_65r_padus@report', 'figab_65r_padus@report', 'flwo_65r_padus@report', 'fp_65r_padus@report', 'fril_65r_padus@report', 'fs_65r_padus@report',
# not ran: 'fva_65r_padus@report',
# ran: 'gorjac_65r_padus@report', 'graf_65r_padus@report', 'gray_65r_padus@report', 
# not ran: 'huach_65r_padus@report', 'irwin_65r_padus@report',
def main():
    for map in [  'jblm_cr_65r_padus@report', 'knox_65r_padus@report', 'mccoy_65r_padus@report', 'mta_65r_padus@report', 'orch_65r_padus@report', 'rave_65r_padus@report', 'rip_65r_padus@report', 'shel_65r_padus@report', 'sill_65r_padus@report', 'west_65r_padus@report']:
        run_command("v.pack",
                    input = map,
                    output = "F:/data/Regional Prioritization/padpack/" + map + ".pack",
                    overwrite = True)



    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
